language: swift
podfile: DKPhotoGalleryDemo/Podfile

osx_image: xcode9
xcode_sdk: iphonesimulator11.0

before_install:
  - rvm use system
  - sudo gem install cocoapods -v '1.3.1'
  - pod repo update

script:
- xcodebuild clean build test -workspace DKPhotoGalleryDemo/DKPhotoGalleryDemo.xcworkspace -scheme DKPhotoGalleryDemo -destination "platform=iOS Simulator,name=iPhone 7"